spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.1