version: '3.7'

services:
  postgres-db:
    image: postgres:latest  # PostgreSQL 공식 이미지를 사용
    container_name: postgres-db
    environment:
      POSTGRES_USER: taehun  # 데이터베이스 사용자 이름
      POSTGRES_PASSWORD: '1234'  # 데이터베이스 비밀번호
      POSTGRES_DB: order-service  # 생성할 데이터베이스 이름
    ports:
      - "5432:5432"  # PostgreSQL 포트를 호스트와 연결
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # 데이터 지속성을 위해 볼륨 설정

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
