spring:
  application:
    name: hub-service

  data:
    redis:
      host: hub-redis
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/rooibos-hub
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 19100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

naver:
  coordinate:
    id: ${API_KEY_ID}
    secret: ${API_SECRET_KEY}