server:
  port: 19091  # ????? ???? ??? ?? ??

spring:
  main:
    web-application-type: reactive  # Spring ??????? ???? ? ???????? ???
  application:
    name: gateway-service  # ?????? ??? 'gateway-service'? ??
  cloud:
    gateway:
      routes:
        - id: auth-service  # ??? ???
          uri: lb://auth-service  # 'auth-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/auth/**  # /auth/signIn ??? ???? ??? ? ???? ??
        - id: user-service  # ??? ???
          uri: lb://user-service  # 'auth-service'?? ???? ?? ???? ???? ???
          predicates:
            - Path=/user/**  # /auth/signIn ??? ???? ??? ? ???? ??
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ????? ??
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"

  data:
    redis:
      host: redis-user
      port: 6379
      username: default
      password: systempass

jwt:
  secret: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
#  white-list:
#    - /user/signIn
#    - /auth/longin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka ??? URL? ??

management:
  endpoints:
    web:
      exposure:
        include: "*"