server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/hub/**
        - id: route-service
          uri: lb://route-service
          predicates:
            - Path=/route/**
      discovery:
        locator:
          enabled: true


  data:
    redis:
      host: redis-user
      port: 6379
      username: default
      password: systempass

jwt:
  secret: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.1