spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-service
    username: taehun
    password: 0858
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090
