spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis-auth
      port: 6379
      username: default
      password: systempass

  jwt:
    secret: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.1

server:
  port: 19092