spring:
  application:
    name: deliverer

  datasource:
    url: jdbc:postgresql://localhost:5432/deliverer-db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/