spring:
  application:
    name: deliverer

  datasource:
    url: jdbc:postgresql://localhost:5432/deliverer
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

server:
  port: 19098

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/