services:
  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-user
    restart: always
    environment:
      REDIS_ARGS: "--requirepass systempass"
    ports:
      - 6380:6379
      - 8002:8001