spring:
  application:
    name: route-service

  data:
    redis:
      host: route_redis
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5440/route_db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: route-server
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

server:
  port: 19101

naver:
  coordinate:
    id: ${API_KEY_ID}
    secret: ${API_SECRET_KEY}

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.1

